version: '3.8'

services:
  # MLflow tracking server
  mlflow:
    image: python:3.9-slim
    container_name: mlflow-server
    entrypoint: >
      bash -c "
        pip install mlflow>=2.0.0 psycopg2-binary &&
        mlflow server --host 0.0.0.0 --backend-store-uri /mlruns"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    # Command is now included in the entrypoint

  # Model training service
  training:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-recommendation-training
    volumes:
      - ./:/app
      - ./mlruns:/mlruns
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: python main.py --optimize --register_model
    
  # Model registration service
  model-registration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-recommendation-registration
    volumes:
      - ./:/app
      - ./mlruns:/mlruns
    depends_on:
      - training
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: python register_model.py
    profiles:
      - post-training

  # FastAPI service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-recommendation-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./mlruns:/mlruns
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=car-recommendation-model
      - MODEL_STAGE=Production
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload